#!/bin/bash
set -euo pipefail
cd "`dirname "$0"`/.."

source ./scripts/tag-vars
echo $EXPO_TAG
echo $ANDROID_TAG
echo $IOS_TAG

# maybe delete the tags, if they exist...?
git tag -d $EXPO_TAG || true
git tag -d $ANDROID_TAG || true
git tag -d $IOS_TAG || true