#!/bin/bash
set -euo pipefail
cd "`dirname "$0"`/.."

source ./scripts/tag-vars
echo $EXPO_TAG
echo $ANDROID_TAG
echo $IOS_TAG

# don't overwrite android- and ios-version tags, those are permanenet
git push origin $ANDROID_TAG
git push origin $IOS_TAG
# user-visible version tags 
git push -f origin $EXPO_TAG
