name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    # https://github.com/expo/expo-github-action
    # using their action avoids ENOSPC: https://github.com/expo/expo-github-action/issues/20
    - uses: expo/expo-github-action@v5
      with:
        expo-version: 3.x
        expo-username: erosson
        expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
    - run: yarn --dev --frozen-lockfile
    - run: yarn test
    - run: yarn deploy  # `expo publish` plus some prepublish chores
